name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}) on ubuntu-latest
    runs-on: 'ubuntu-latest' 
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8']


    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[test]
      - name: Test
        shell: bash -l {0}
        run: |
          pytest